// Mocks generated by Mockito 5.4.6 from annotations
// in echoes/test/homepage_controller_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;
import 'dart:typed_data' as _i8;
import 'dart:ui' as _i6;

import 'package:echoes/controllers/location_service.dart' as _i7;
import 'package:google_maps_flutter/google_maps_flutter.dart' as _i3;
import 'package:location/location.dart' as _i4;
import 'package:location_platform_interface/location_platform_interface.dart'
    as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeLocationData_0 extends _i1.SmartFake implements _i2.LocationData {
  _FakeLocationData_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatLngBounds_1 extends _i1.SmartFake implements _i3.LatLngBounds {
  _FakeLatLngBounds_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeScreenCoordinate_2 extends _i1.SmartFake
    implements _i3.ScreenCoordinate {
  _FakeScreenCoordinate_2(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeLatLng_3 extends _i1.SmartFake implements _i3.LatLng {
  _FakeLatLng_3(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [Location].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocation extends _i1.Mock implements _i4.Location {
  @override
  _i5.Stream<_i2.LocationData> get onLocationChanged =>
      (super.noSuchMethod(
            Invocation.getter(#onLocationChanged),
            returnValue: _i5.Stream<_i2.LocationData>.empty(),
            returnValueForMissingStub: _i5.Stream<_i2.LocationData>.empty(),
          )
          as _i5.Stream<_i2.LocationData>);

  @override
  _i5.Future<bool> changeSettings({
    _i2.LocationAccuracy? accuracy = _i2.LocationAccuracy.high,
    int? interval = 1000,
    double? distanceFilter = 0.0,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeSettings, [], {
              #accuracy: accuracy,
              #interval: interval,
              #distanceFilter: distanceFilter,
            }),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> isBackgroundModeEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#isBackgroundModeEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> enableBackgroundMode({bool? enable = true}) =>
      (super.noSuchMethod(
            Invocation.method(#enableBackgroundMode, [], {#enable: enable}),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.LocationData> getLocation() =>
      (super.noSuchMethod(
            Invocation.method(#getLocation, []),
            returnValue: _i5.Future<_i2.LocationData>.value(
              _FakeLocationData_0(this, Invocation.method(#getLocation, [])),
            ),
            returnValueForMissingStub: _i5.Future<_i2.LocationData>.value(
              _FakeLocationData_0(this, Invocation.method(#getLocation, [])),
            ),
          )
          as _i5.Future<_i2.LocationData>);

  @override
  _i5.Future<_i2.PermissionStatus> hasPermission() =>
      (super.noSuchMethod(
            Invocation.method(#hasPermission, []),
            returnValue: _i5.Future<_i2.PermissionStatus>.value(
              _i2.PermissionStatus.granted,
            ),
            returnValueForMissingStub: _i5.Future<_i2.PermissionStatus>.value(
              _i2.PermissionStatus.granted,
            ),
          )
          as _i5.Future<_i2.PermissionStatus>);

  @override
  _i5.Future<_i2.PermissionStatus> requestPermission() =>
      (super.noSuchMethod(
            Invocation.method(#requestPermission, []),
            returnValue: _i5.Future<_i2.PermissionStatus>.value(
              _i2.PermissionStatus.granted,
            ),
            returnValueForMissingStub: _i5.Future<_i2.PermissionStatus>.value(
              _i2.PermissionStatus.granted,
            ),
          )
          as _i5.Future<_i2.PermissionStatus>);

  @override
  _i5.Future<bool> serviceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#serviceEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> requestService() =>
      (super.noSuchMethod(
            Invocation.method(#requestService, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i2.AndroidNotificationData?> changeNotificationOptions({
    String? channelName,
    String? title,
    String? iconName,
    String? subtitle,
    String? description,
    _i6.Color? color,
    bool? onTapBringToFront,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#changeNotificationOptions, [], {
              #channelName: channelName,
              #title: title,
              #iconName: iconName,
              #subtitle: subtitle,
              #description: description,
              #color: color,
              #onTapBringToFront: onTapBringToFront,
            }),
            returnValue: _i5.Future<_i2.AndroidNotificationData?>.value(),
            returnValueForMissingStub:
                _i5.Future<_i2.AndroidNotificationData?>.value(),
          )
          as _i5.Future<_i2.AndroidNotificationData?>);
}

/// A class which mocks [LocationService].
///
/// See the documentation for Mockito's code generation for more information.
class MockLocationService extends _i1.Mock implements _i7.LocationService {
  @override
  _i5.Future<bool> ensureServiceEnabled() =>
      (super.noSuchMethod(
            Invocation.method(#ensureServiceEnabled, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<bool> ensurePermissionGranted() =>
      (super.noSuchMethod(
            Invocation.method(#ensurePermissionGranted, []),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<_i3.LatLng?> getUserLocationCoords() =>
      (super.noSuchMethod(
            Invocation.method(#getUserLocationCoords, []),
            returnValue: _i5.Future<_i3.LatLng?>.value(),
            returnValueForMissingStub: _i5.Future<_i3.LatLng?>.value(),
          )
          as _i5.Future<_i3.LatLng?>);

  @override
  _i5.Stream<_i3.LatLng> getLocationStream() =>
      (super.noSuchMethod(
            Invocation.method(#getLocationStream, []),
            returnValue: _i5.Stream<_i3.LatLng>.empty(),
            returnValueForMissingStub: _i5.Stream<_i3.LatLng>.empty(),
          )
          as _i5.Stream<_i3.LatLng>);
}

/// A class which mocks [GoogleMapController].
///
/// See the documentation for Mockito's code generation for more information.
class MockGoogleMapController extends _i1.Mock
    implements _i3.GoogleMapController {
  @override
  int get mapId =>
      (super.noSuchMethod(
            Invocation.getter(#mapId),
            returnValue: 0,
            returnValueForMissingStub: 0,
          )
          as int);

  @override
  _i5.Future<void> clearTileCache(_i3.TileOverlayId? tileOverlayId) =>
      (super.noSuchMethod(
            Invocation.method(#clearTileCache, [tileOverlayId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> animateCamera(
    _i3.CameraUpdate? cameraUpdate, {
    Duration? duration,
  }) =>
      (super.noSuchMethod(
            Invocation.method(
              #animateCamera,
              [cameraUpdate],
              {#duration: duration},
            ),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> moveCamera(_i3.CameraUpdate? cameraUpdate) =>
      (super.noSuchMethod(
            Invocation.method(#moveCamera, [cameraUpdate]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> setMapStyle(String? mapStyle) =>
      (super.noSuchMethod(
            Invocation.method(#setMapStyle, [mapStyle]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<String?> getStyleError() =>
      (super.noSuchMethod(
            Invocation.method(#getStyleError, []),
            returnValue: _i5.Future<String?>.value(),
            returnValueForMissingStub: _i5.Future<String?>.value(),
          )
          as _i5.Future<String?>);

  @override
  _i5.Future<_i3.LatLngBounds> getVisibleRegion() =>
      (super.noSuchMethod(
            Invocation.method(#getVisibleRegion, []),
            returnValue: _i5.Future<_i3.LatLngBounds>.value(
              _FakeLatLngBounds_1(
                this,
                Invocation.method(#getVisibleRegion, []),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.LatLngBounds>.value(
              _FakeLatLngBounds_1(
                this,
                Invocation.method(#getVisibleRegion, []),
              ),
            ),
          )
          as _i5.Future<_i3.LatLngBounds>);

  @override
  _i5.Future<_i3.ScreenCoordinate> getScreenCoordinate(_i3.LatLng? latLng) =>
      (super.noSuchMethod(
            Invocation.method(#getScreenCoordinate, [latLng]),
            returnValue: _i5.Future<_i3.ScreenCoordinate>.value(
              _FakeScreenCoordinate_2(
                this,
                Invocation.method(#getScreenCoordinate, [latLng]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.ScreenCoordinate>.value(
              _FakeScreenCoordinate_2(
                this,
                Invocation.method(#getScreenCoordinate, [latLng]),
              ),
            ),
          )
          as _i5.Future<_i3.ScreenCoordinate>);

  @override
  _i5.Future<_i3.LatLng> getLatLng(_i3.ScreenCoordinate? screenCoordinate) =>
      (super.noSuchMethod(
            Invocation.method(#getLatLng, [screenCoordinate]),
            returnValue: _i5.Future<_i3.LatLng>.value(
              _FakeLatLng_3(
                this,
                Invocation.method(#getLatLng, [screenCoordinate]),
              ),
            ),
            returnValueForMissingStub: _i5.Future<_i3.LatLng>.value(
              _FakeLatLng_3(
                this,
                Invocation.method(#getLatLng, [screenCoordinate]),
              ),
            ),
          )
          as _i5.Future<_i3.LatLng>);

  @override
  _i5.Future<void> showMarkerInfoWindow(_i3.MarkerId? markerId) =>
      (super.noSuchMethod(
            Invocation.method(#showMarkerInfoWindow, [markerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<void> hideMarkerInfoWindow(_i3.MarkerId? markerId) =>
      (super.noSuchMethod(
            Invocation.method(#hideMarkerInfoWindow, [markerId]),
            returnValue: _i5.Future<void>.value(),
            returnValueForMissingStub: _i5.Future<void>.value(),
          )
          as _i5.Future<void>);

  @override
  _i5.Future<bool> isMarkerInfoWindowShown(_i3.MarkerId? markerId) =>
      (super.noSuchMethod(
            Invocation.method(#isMarkerInfoWindowShown, [markerId]),
            returnValue: _i5.Future<bool>.value(false),
            returnValueForMissingStub: _i5.Future<bool>.value(false),
          )
          as _i5.Future<bool>);

  @override
  _i5.Future<double> getZoomLevel() =>
      (super.noSuchMethod(
            Invocation.method(#getZoomLevel, []),
            returnValue: _i5.Future<double>.value(0.0),
            returnValueForMissingStub: _i5.Future<double>.value(0.0),
          )
          as _i5.Future<double>);

  @override
  _i5.Future<_i8.Uint8List?> takeSnapshot() =>
      (super.noSuchMethod(
            Invocation.method(#takeSnapshot, []),
            returnValue: _i5.Future<_i8.Uint8List?>.value(),
            returnValueForMissingStub: _i5.Future<_i8.Uint8List?>.value(),
          )
          as _i5.Future<_i8.Uint8List?>);

  @override
  void dispose() => super.noSuchMethod(
    Invocation.method(#dispose, []),
    returnValueForMissingStub: null,
  );
}
